### ISSUE TITLE
thread support

### ISSUE THREAD

**Issue by klemens-morgenstern** [klemens-morgenstern/async#19]
The library is currently strictly single threaded, and the former `async::thread` class has been removed. If we want multi-threading we need would need synchronization primitives, such as mutex etc. (the `sam` stuff, but simpler).

Potentially also thread-safe channels.

**Comment by ned14** [comment]
Surely the bare minimum viable support needed here is to reparent something from one executor to another? You can build anything else you want on top of that.

**Comment by jsaf0** [comment]
Simple synchronization primitives like `Event` and `Lock` from Python’s asyncio (https://docs.python.org/3/library/asyncio-sync.html) would still be very convenient to have as part of this library - also in a single-threaded context.

**Comment by klemens-morgenstern** [comment]
This was the thread type (that can be restored): https://github.com/klemens-morgenstern/async/commit/a7fe353dfc550e4a4393a1bc24396f648cca6826

```cpp
boost::async::thread thr()
{
  boost::asio::steady_timer tim{co_await boost::asio::this_coro::executor, std::chrono::milliseconds(100)};

  auto exec = co_await boost::asio::this_coro::executor;
  co_await tim.async_wait(boost::asio::deferred);
}

boost::async::main co_main(int argc, char ** argv)
{

   co_await thr();
   co_return 0;
}
```

**Comment by klemens-morgenstern** [comment]
Actually all we need in addition is to be able to safely have `co_await` cross executors:

```cpp
boost::async::thread thr(async::channel<int> foreign_channel) // < different executor
{
  co_await thread_safe(foreign_channel.read()); // has an associated executor
  co_await thread_safe(foreign_channel.get_executor(), foreign_channel.read());
}
```

**Comment by klemens-morgenstern** [comment]
Alternatively we could have a coro that is attached to a thread but can be awaited safely, like this:

```cpp

thread::safe coro(thread & thread_to_run_on)
{
  // everything in here runs on `thread_to_run_on`
   co_await 
}
```

**Comment by klemens-morgenstern** [comment]
@madmongo1

**Comment by klemens-morgenstern** [comment]
Added an spsc-queue example, we don't need this with unique_handle and the other stuff being in the code.

**Comment by pfeatherstone** [comment]
I'm struggling to see why threading has become an issue here, and why we would need synchronization primitives. I'm not an expert like you guys, so that's likely why... However, in Asio, you can use `awaitable` or `coro` in a multi-threaded environment safely, provided you carefully choose your executors, e.g. implicit/explicit strands, or channels. Moreover, users can "bring their own threads" by simply calling `asio::io_context::run` on multiple threads. You don't have to use special threads. I feel like this is causing more confusion to asio users. Maybe cppalliance's book on asio, concurrency and coroutines is much needed. What were @chriskohlhoff 's comments on this library? Thank you everyone for the fantastic work!
